"""initial models

Revision ID: 5c161cbbac02
Revises: 
Create Date: 2018-08-19 23:12:44.246110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c161cbbac02'
down_revision = None
branch_labels = ('flaskbb_ranks',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ranks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rank_code', sa.String(length=255), nullable=False),
    sa.Column('rank_name', sa.String(length=255), nullable=True),
    sa.Column('requirement', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ranks')),
    sa.UniqueConstraint('requirement', name=op.f('uq_ranks_requirement'))
    )
    op.create_table('user_rank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rank_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['rank_id'], ['ranks.id'], name=op.f('fk_user_rank_rank_id_ranks')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_rank_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_rank'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_rank')
    op.drop_table('ranks')
    # ### end Alembic commands ###
