language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
env:
matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: TOXENV=py27-unpinned
    - python: 3.6
      env: TOXENV=flake8
    - python: 3.6
      env: TOXENV=py36-unpinned
    - python: 3.6
      env: TOXENV=black
    # see the following issue on why 3.7 is weirdo
    # https://github.com/travis-ci/travis-ci/issues/9815
    - python: 3.7
      dist: xenial
      sudo: true
install:
    - pip install -r requirements-travis.txt
script:
    - tox
after_success:
    - coverage combine tests
    - coveralls
notifications:
  webhooks: https://www.travisbuddy.com/
  on_success: never
